# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.0.1
# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: circleci/python:3.8.4-browsers
    steps:
      - browser-tools/install-geckodriver
      - checkout
      - run: pip install -r requirements.txt
      - run: python ./src/testset_webpage_with_selenium.py
      - run: locust -f ./src/testset_load_with_locust.py --user 1 --hatch-rate 1 --headless --run-time 1m --host https://dog.ceo

# Orchestrate our job run sequence
workflows:
  run_tests:
    jobs:
      - test